### PR TITLE
Allow online custon layers

### PR DESCRIPTION
**Pull request by fsdavid**

### CODE REVIEW

**Comment by fsdavid** [comment]
@xgui3783 It works and ready to merge

**Comment by xgui3783** [comment]
Can you add the feature to release notes?

**Comment by fsdavid** [comment]
Yes, I will add.

**Comment by xgui3783** [comment]
three things:

1/ the custom layer does not need to be nifti. It can be precomputed, swc, etc. 
2/ if you want to push changes without triggering CI ,you can add `[skip ci]` to the start of the commit message. (In this case, release notes does not need to trigger CI (at least not yet)
3/ can you resolve the merge conflicts?

**Comment by xgui3783** [comment]
@fsdavid re [dc06157](https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1265/commits/dc06157ce703ad2322610ad2c976e606b6960507), it does not need to be precomputed either. 

It's better that we clarify the release notes to say that it supports arbitrary layer based on URL parameter.

**Pull request merged**
