### PR TITLE
Configuration changes to display MGB

### PR DESCRIPTION
**Pull request by ch-schiffer**

### CODE REVIEW

**Comment by xgui3783** [comment]
@ch-schiffer you might also want to update the relevant sections under https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations

**Comment by ch-schiffer** [comment]
Added another commit to specify color, the random color generated all new areas in the same color.
Also, there is currently no related information displayed for the new areas. Is this expected, as the respective KG cards are not yet available?

**Comment by xgui3783** [comment]
> Also, there is currently no related information displayed for the new areas. Is this expected, as the respective KG cards are not yet available?

That is correct. Once the region is registered within KG, and added to `fullId.kg` attribute, relevant datasets can then be retrieved.

Also, since I merged the PR prior to the new commit, would you like to raise a new PR?

**Comment by ch-schiffer** [comment]
Okay, thanks for the info! I created a new PR for the color changes.

Which branch is relevant if I want to update https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations?

**Comment by xgui3783** [comment]
Hmm, best to ask Timo, but `develop` is a good bet.

It will be more formalised in the future.

**Comment by ch-schiffer** [comment]
Everything looks fine in the staging area, changes can be deployed to production.

**Pull request merged**
