### PR TITLE
Add viewer settings on the settings window

### PR DESCRIPTION
**Pull request by fsdavid**

### CODE REVIEW

**Comment by xgui3783** [comment]
is this duplicate for #1148 ?

**Comment by fsdavid** [comment]
Yes, it is. I was going to close it after fixing comments. I will close it now.

**Comment by xgui3783** [comment]
It looks like so. 

I just merged staging -> dev. 

Can you add your commit on top of exisitng dev?

I will work on a workflow that automatically merge to dev on release.

**Comment by fsdavid** [comment]
Yes sure, or I will just reopen #1148

**Pull request closed without merging**
