### PR TITLE
View connectivity dataset modal

### PR DESCRIPTION
**Pull request by fsdavid**

### CODE REVIEW

**Review by xgui3783 — APPROVED** [review]
LGTM

**Comment by xgui3783** [comment]
PR looks fine, but deploy looks weird: https://siibra-explorer.apps.hbp.eu/fixconndatasetview

**Comment by fsdavid** [comment]
> PR looks fine, but deploy looks weird: https://siibra-explorer.apps.hbp.eu/fixconndatasetview

For me it doesn't work at all:
image

**Comment by xgui3783** [comment]
> > PR looks fine, but deploy looks weird: https://siibra-explorer.apps.hbp.eu/fixconndatasetview
> 
> For me it doesn't work at all:

that's what I meant

**Comment by xgui3783** [comment]
ok found the bug. will fix

**Pull request merged**
