### PR TITLE
Fix connectivity version on production

### PR DESCRIPTION
**Pull request by fsdavid**

### CODE REVIEW

**Comment by fsdavid** [comment]
@xgui3783 Do I need to do something more to merge this change to production?

**Comment by xgui3783** [comment]
In the future, it would be better to follow semver (x.y.z) (where major breaking changes increment x, minor, non breaking changes increment y and bugfixes increment z)

Can you increment package.json to the next bugfix version, and add release notes?

**Comment by xgui3783** [comment]
also for discussion:

instead of including the connectivity component as an npm dependency, can we just include it from unpkg, similar to https://github.com/FZJ-INM1-BDA/siibra-explorer/blob/master/src/index.html#L16 ?

**Comment by fsdavid** [comment]
Sure :)

**Comment by xgui3783** [comment]
I forgot, but can you also update mkdocs.yml?

**Comment by fsdavid** [comment]
> I forgot, but can you also update mkdocs.yml?

Oh sorry. I forgot.

**Comment by fsdavid** [comment]
@xgui3783 Do I need some more changes to merge PR to production?

**Pull request merged**
