### PR TITLE
Fix space key behaviour on full view

### PR DESCRIPTION
**Pull request by fsdavid**

### CODE REVIEW

**Comment by xgui3783** [comment]
Hmm, I will have to think about this briefly.

I am not too happy on how the spacebar listener was implemented.

**Comment by fsdavid** [comment]
What do you think to merge PR as the fix of the production and change the logic in the dev version? The issue happens not only on annotation mode but any input text, like both region searches.

**Comment by xgui3783** [comment]
I briefly remember implementing fix so that region search does not result in cycling view.

What I don't want is to have 2 solutions for the same problem.

**Comment by fsdavid** [comment]
As I see production version still has bugs for region searches both on the sidebar and region hierarchy. Also as you mentioned it is the global problem of how spacebar listener works. I think implementing fixes of each separate component would not be the best way in such kind of situation.

**Comment by xgui3783** [comment]
Hmm, that is true. There had been regressions.

But I think rather than checking `(ev.target as HTMLElement).classList.contains('neuroglancer-panel')`, we should check if ev.target === input // text area

I feel very hesitant to hard code class. 

at the same time, I wonder if the event listener should be in the service at all.

**Comment by xgui3783** [comment]
don't make any edits yet, I need to review how it is implemented currently

**Comment by fsdavid** [comment]
Ok. If you will be agree I could change code with ```!['input', 'textarea'].includes((ev.target as HTMLElement).tagName.toLowerCase())```

**Comment by fsdavid** [comment]
@xgui3783 What do you think may I use some different approaches to make a quick fix for tomorrow's workshop?

**Comment by xgui3783** [comment]
In lieu with the urgency of the issue, let's merge this for now.

we can undo and revisit this issue at a later date.

**Pull request merged**
