### PR TITLE
Show mini perspective on maximised slice views

### PR DESCRIPTION
**Pull request by fsdavid**

### CODE REVIEW

**Comment by xgui3783** [comment]
can you remind me what this PR is suppose to do?

**Comment by fsdavid** [comment]
> can you remind me what this PR is suppose to do?

It should show a mini perspective view (with slider) when slice views are maximized

**Comment by xgui3783** [comment]
> > can you remind me what this PR is suppose to do?
> 
> It should show a mini perspective view (with slider) when slice views are maximized

can you rename the PR accordingly then?

also, does this PR supercede https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1089 ?

**Comment by fsdavid** [comment]
Yes, it's supercede #1089 . I've closed that PR

**Comment by fsdavid** [comment]
Issue: https://github.com/FZJ-INM1-BDA/siibra/issues/44

**Comment by xgui3783** [comment]
@fsdavid , sorry I missed reviewing this PR. 

Can you rebase your changes to the current dev? there are way too many merge conflicts for now. 

(when you push new commits, the docker image should also rebuild, and the preview link should then work again)

**Comment by fsdavid** [comment]
@xgui3783 Sure, I will rebase the branch :)

**Comment by fsdavid** [comment]
Actually, this branch is moved here: https://github.com/FZJ-INM1-BDA/siibra-explorer/pull/1180
Sorry, I will close this one.

**Pull request closed without merging**
