### PR TITLE
bugfix: setting custom layer overwrites exsting layers

### PR DESCRIPTION
**Pull request by xgui3783**
chore: added prettierrc

### CODE REVIEW

**Comment by xgui3783** [comment]
@fsdavid I have made some changes to custom layers

instead of using queryparam, it now uses specific path (since it's more straight forward with the existing `customRoute` functionality.

now, by appending `/x-overlaylayer:${encodeUriComponent('nifti://http://localhost:3000/test.nii.gz')}`, one can overlay any volume on existing atlas

**Comment by fsdavid** [comment]
Should tests be fixed before the merge?

**Comment by xgui3783** [comment]
yes, I am looking into it

in the mean time, can you check the others?

**Comment by fsdavid** [comment]
Sure

**Pull request merged**
